"""add embedding columns for cross-language clustering

Revision ID: 05a0c72336ee
Revises: fcc5ec3b8595
Create Date: 2026-08-03 20:31:08.212009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05a0c72336ee'
down_revision: Union[str, Sequence[str], None] = 'fcc5ec3b8595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_cluster', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('raw_item', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_item', 'embedding')
    op.drop_column('news_cluster', 'embedding')
    # ### end Alembic commands ###
