"""add draft handoff_note for snooze

Revision ID: 654d4faeef77
Revises: ced7cc66d125
Create Date: 2026-08-04 22:47:01.303097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654d4faeef77'
down_revision: Union[str, Sequence[str], None] = 'ced7cc66d125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('handoff_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'handoff_note')
    # ### end Alembic commands ###
