"""add draft pending_category_slug for phase 7 approve flow

Revision ID: bd8c1fb1b825
Revises: 654d4faeef77
Create Date: 2026-08-05 00:01:23.186197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8c1fb1b825'
down_revision: Union[str, Sequence[str], None] = '654d4faeef77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('pending_category_slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'pending_category_slug')
    # ### end Alembic commands ###
