"""compliance gate fields + admin settings tables

Revision ID: ced7cc66d125
Revises: 05a0c72336ee
Create Date: 2026-08-04 09:18:26.154411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ced7cc66d125'
down_revision: Union[str, Sequence[str], None] = '05a0c72336ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_rotation_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_rotation_model')),
    sa.UniqueConstraint('model_id', name=op.f('uq_llm_rotation_model_model_id'))
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic')),
    sa.UniqueConstraint('name', name=op.f('uq_topic_name'))
    )
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_app_setting_updated_by_user')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    # server_default backfills existing rows in the same statement — the
    # `draft` table is not empty in prod (live Phase 4 dispatcher), so a
    # bare NOT NULL add_column fails on the existing rows without it.
    op.add_column(
        'draft',
        sa.Column('sensitive_hold', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'draft',
        sa.Column(
            'compliance_notes', postgresql.ARRAY(sa.Text()), nullable=False, server_default='{}'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'compliance_notes')
    op.drop_column('draft', 'sensitive_hold')
    op.drop_table('app_setting')
    op.drop_table('topic')
    op.drop_table('llm_rotation_model')
    # ### end Alembic commands ###
