"""initial schema

Revision ID: fcc5ec3b8595
Revises:
Create Date: 2026-08-03 17:01:12.632225

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcc5ec3b8595'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_research_cache',
    sa.Column('normalized_phrase', sa.String(length=512), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('related', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('normalized_phrase', 'locale', 'provider', name=op.f('pk_keyword_research_cache'))
    )
    op.create_table('llm_rotation_state',
    sa.Column('key_alias', sa.String(length=32), nullable=False),
    sa.Column('current_model_index', sa.Integer(), nullable=False),
    sa.Column('last_switched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_alias', name=op.f('pk_llm_rotation_state'))
    )
    op.create_table('llm_rotation_usage',
    sa.Column('key_alias', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key_alias', 'model', name=op.f('pk_llm_rotation_usage'))
    )
    op.create_table('news_cluster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('topic_status', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_cluster'))
    )
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    op.create_table('tag_category_cache',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_category_cache'))
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_audit_log_actor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('cluster_context',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('press_release', sa.Boolean(), nullable=False),
    sa.Column('regulated', sa.Boolean(), nullable=False),
    sa.Column('market_sensitive', sa.Boolean(), nullable=False),
    sa.Column('fact_conflict', sa.Boolean(), nullable=False),
    sa.Column('fact_conflict_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_cluster.id'], name=op.f('fk_cluster_context_cluster_id_news_cluster')),
    sa.PrimaryKeyConstraint('cluster_id', name=op.f('pk_cluster_context'))
    )
    op.create_table('prompt_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_prompt_version_approved_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_version'))
    )
    op.create_table('raw_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_full_text', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_manual_inject', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_cluster.id'], name=op.f('fk_raw_item_cluster_id_news_cluster')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_raw_item_source_id_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_item')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_raw_item_source_external_id')
    )
    op.create_table('rewriter_style_cache',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('preferences_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rewriter_style_cache_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_rewriter_style_cache'))
    )
    op.create_table('draft',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('title_ru', sa.Text(), nullable=False),
    sa.Column('body_ru', sa.Text(), nullable=False),
    sa.Column('title_en_variants', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('title_ru_variants', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('attribution_urls', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('sponsor_flag', sa.Boolean(), nullable=False),
    sa.Column('press_release_flag', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_flag', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('fact_conflict', sa.Boolean(), nullable=False),
    sa.Column('rewrite_llm_key_alias', sa.String(length=32), nullable=True),
    sa.Column('rewrite_llm_model', sa.String(length=255), nullable=True),
    sa.Column('translate_llm_key_alias', sa.String(length=32), nullable=True),
    sa.Column('translate_llm_model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('seo_title_en', sa.String(length=512), nullable=True),
    sa.Column('seo_description_en', sa.Text(), nullable=True),
    sa.Column('slug_en', sa.String(length=512), nullable=True),
    sa.Column('og_title_en', sa.String(length=512), nullable=True),
    sa.Column('og_description_en', sa.Text(), nullable=True),
    sa.Column('focus_keyphrase_en', sa.String(length=255), nullable=True),
    sa.Column('keywords_en', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('seo_title_ru', sa.String(length=512), nullable=True),
    sa.Column('seo_description_ru', sa.Text(), nullable=True),
    sa.Column('slug_ru', sa.String(length=512), nullable=True),
    sa.Column('og_title_ru', sa.String(length=512), nullable=True),
    sa.Column('og_description_ru', sa.Text(), nullable=True),
    sa.Column('focus_keyphrase_ru', sa.String(length=255), nullable=True),
    sa.Column('keywords_ru', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('image_brief', sa.Text(), nullable=True),
    sa.Column('image_mood', sa.String(length=255), nullable=True),
    sa.Column('image_subjects', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('image_style', sa.String(length=255), nullable=True),
    sa.Column('image_do_not', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('image_alt', sa.String(length=512), nullable=True),
    sa.Column('image_caption', sa.Text(), nullable=True),
    sa.Column('image_source_suggestion', sa.String(length=512), nullable=True),
    sa.Column('image_license_confirmed', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('tag_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('pending_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['user.id'], name=op.f('fk_draft_assignee_user_id_user')),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_cluster.id'], name=op.f('fk_draft_cluster_id_news_cluster')),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_version.id'], name=op.f('fk_draft_prompt_version_id_prompt_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft'))
    )
    op.create_table('draft_lock',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('fk_draft_lock_draft_id_draft')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_draft_lock_user_id_user')),
    sa.PrimaryKeyConstraint('draft_id', 'user_id', name=op.f('pk_draft_lock'))
    )
    op.create_index('uq_draft_lock_one_editor_per_draft', 'draft_lock', ['draft_id'], unique=True, postgresql_where=sa.text("mode = 'editing'"))
    op.create_table('draft_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('title_ru', sa.Text(), nullable=False),
    sa.Column('body_ru', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_draft_revision_author_id_user')),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('fk_draft_revision_draft_id_draft')),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_version.id'], name=op.f('fk_draft_revision_prompt_version_id_prompt_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_revision'))
    )
    op.create_table('edit_signal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_edit_signal_author_id_user')),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('fk_edit_signal_draft_id_draft')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edit_signal'))
    )
    op.create_table('publish_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('tag_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('fk_publish_record_draft_id_draft')),
    sa.ForeignKeyConstraint(['published_by'], ['user.id'], name=op.f('fk_publish_record_published_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_record'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publish_record')
    op.drop_table('edit_signal')
    op.drop_table('draft_revision')
    op.drop_index('uq_draft_lock_one_editor_per_draft', table_name='draft_lock', postgresql_where=sa.text("mode = 'editing'"))
    op.drop_table('draft_lock')
    op.drop_table('draft')
    op.drop_table('rewriter_style_cache')
    op.drop_table('raw_item')
    op.drop_table('prompt_version')
    op.drop_table('cluster_context')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('tag_category_cache')
    op.drop_table('source')
    op.drop_table('news_cluster')
    op.drop_table('llm_rotation_usage')
    op.drop_table('llm_rotation_state')
    op.drop_table('keyword_research_cache')
    # ### end Alembic commands ###
